#!/usr/bin/env bash
# Transfers a file from our client to a server
# Accepts 4 parameters:
# 1. The path to the file to be transferred
# 2. The IP of the server we want to transfer the file to
# 3. The username scp connects with
# 4. The path to the SSH private key that scp uses

#checking the parameters to ensure all four as above
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # scp must transfer the file to the user home directory ~/
  # Disable strict host key
  # PATH_TO_FILE="$1"
  # IP="$2"
  # USERNAME="$3"
  # SSH_KEY="$4"
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
