#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx

# listen on port 80
sudo ufw allow 'Nginx HTTP'

#create web page with custom text
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
