#!/usr/bin/env bash

# Update the package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow incoming traffic on port 80 (HTTP) using UFW (Uncomplicated Firewall)
sudo ufw allow 'Nginx HTTP'

# Create a custom HTML file with "Hello World!" message
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
# Start the Nginx service
sudo systemctl start nginx
