#!/usr/bin/env bash

# Update the package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow incoming traffic on port 80 (HTTP) using UFW (Uncomplicated Firewall)
sudo ufw allow 'Nginx HTTP'

# Create a custom HTML file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Start the Nginx service
sudo systemctl start nginx

# Enable Nginx to start on boot (optional)
sudo systemctl enable nginx

# Display a message indicating that Nginx is installed and running
echo "Nginx has been installed and is running."
