#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

lines="\nfrontend frontend_server\n\tbind *:80\n\tdefault_backend backend_server\n\nbackend backend_server\n\tbalance roundrobin\n\tserver 251811-web-01 100.26.157.101:80 check\n\tserver 251811-web-02 54.157.150.183:80 check"

echo -e "$lines" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart