#!/usr/bin/env bash
# Fizzbuzz

count=1

while [ "$count" -le 100 ]; do


  if ! (( count % 3 )) && ! (( count % 5 )); then
    echo "FizzBuzz"
  elif ! (( count % 3 )); then
    echo "Fizz"
  elif ! (( count % 5 )); then
    echo "Buzz"
  else
    echo "$count"
  fi
  
  ((count++))
done