#!/usr/bin/env bash
#displays Best School 10 times.
count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo "4"
            echo "and then bad luck from China"
            ;;
        9)
            echo "9"
            echo "and then bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "and then bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    ((count++))
done