#!/usr/bin/env bash
#displays clock.
hour=0

while [ $hour -le 12 ]; do
    minute=1
    echo "hour: $hour"
    while [ $minute -lt 60 ]; do
        echo "$minute"
        minute=$((minute + 1))
       
    done
    hour=$((hour +1))

done
