#!/usr/bin/env bash
#displays clock.
hour=0

while [ $hour -lt 12 ]; do
    minute=1
    echo "hour: $hour"
    while [ $minute -lt 60 ]; do
        echo "$minute"
        if [ $minute -le 59 ]; then
            ((minute++))
        fi
    done
    ((hour++))

done
