#!/usr/bin/env bash
#displays clock.
hour=0

while [ $hour -lt 12 ]; do
    minute=0
    echo "hour: $hour"
    while [ $minute -le 59 ]; do
        ((minute++))
        if [ $minute -lt 60 ]; then
            echo "$minute"
        fi
    done
    ((hour++))

done
